Rails/Blog/config/routes.rb
Rails.application.routes.draw do
  resources :bookmanages
  root 'home#index'
  get 'home/post'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

Rails/Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Rails/Blog/app/models/bookmanage.rb
class Bookmanage < ApplicationRecord
end

Rails/Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails/Blog/app/controllers/bookmanages_controller.rb
class BookmanagesController < ApplicationController
  before_action :set_bookmanage, only: %i[ show edit update destroy ]

  # GET /bookmanages or /bookmanages.json
  def index
    @bookmanages = Bookmanage.all
  end

  # GET /bookmanages/1 or /bookmanages/1.json
  def show
  end

  # GET /bookmanages/new
  def new
    @bookmanage = Bookmanage.new
  end

  # GET /bookmanages/1/edit
  def edit
  end

  # POST /bookmanages or /bookmanages.json
  def create
    @bookmanage = Bookmanage.new(bookmanage_params)

    respond_to do |format|
      if @bookmanage.save
        format.html { redirect_to bookmanage_url(@bookmanage), notice: "Bookmanage was successfully created." }
        format.json { render :show, status: :created, location: @bookmanage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmanages/1 or /bookmanages/1.json
  def update
    respond_to do |format|
      if @bookmanage.update(bookmanage_params)
        format.html { redirect_to bookmanage_url(@bookmanage), notice: "Bookmanage was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmanage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmanages/1 or /bookmanages/1.json
  def destroy
    @bookmanage.destroy

    respond_to do |format|
      format.html { redirect_to bookmanages_url, notice: "Bookmanage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmanage
      @bookmanage = Bookmanage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmanage_params
      params.require(:bookmanage).permit(:stt, :maHS, :lop, :maSach, :tenSach, :tenTacGia, :ngayMuon, :ngayTra, :soNgay, :ghiChu)
    end
end

Rails/Blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def post
  end

end

Rails/Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Blog/app/helpers/bookmanages_helper.rb
module BookmanagesHelper
end

Rails/Blog/app/helpers/home_helper.rb
module HomeHelper
end

Rails/Blog/app/views/bookmanages/_bookmanage.html.erb
<tr>
  <th scope="row"><%= bookmanage.stt %></th>
  <td><%= bookmanage.maHS %></td>
  <td><%= bookmanage.lop %></td>
  <td><%= bookmanage.maSach %></td>
  <td><%= bookmanage.tenSach %></td>
  <td><%= bookmanage.tenTacGia %></td>
  <td><%= bookmanage.ngayMuon %></td>
  <td><%= bookmanage.ngayTra %></td>
  <td><%= bookmanage.soNgay %></td>
  <td><%= bookmanage.ghiChu %></td>
  <td><p><%= link_to "Chi tiết 146", bookmanage %></p></td>
  <td><p><%= link_to "Sửa 146", edit_bookmanage_path(bookmanage) %></p></td>
</tr>

   

Rails/Blog/app/views/bookmanages/_form.html.erb
<%= form_with(model: bookmanage) do |form| %>
  <% if bookmanage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookmanage.errors.count, "error") %> prohibited this bookmanage from being saved:</h2>

      <ul>
        <% bookmanage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stt, style: "display: block" %>
    <%= form.number_field :stt %>
  </div>

  <div>
    <%= form.label :maHS, style: "display: block" %>
    <%= form.text_field :maHS %>
  </div>

  <div>
    <%= form.label :lop, style: "display: block" %>
    <%= form.text_field :lop %>
  </div>

  <div>
    <%= form.label :maSach, style: "display: block" %>
    <%= form.text_field :maSach %>
  </div>

  <div>
    <%= form.label :tenSach, style: "display: block" %>
    <%= form.text_field :tenSach %>
  </div>

  <div>
    <%= form.label :tenTacGia, style: "display: block" %>
    <%= form.text_field :tenTacGia %>
  </div>

  <div>
    <%= form.label :ngayMuon, style: "display: block" %>
    <%= form.text_field :ngayMuon %>
  </div>

  <div>
    <%= form.label :ngayTra, style: "display: block" %>
    <%= form.text_field :ngayTra %>
  </div>

  <div>
    <%= form.label :soNgay, style: "display: block" %>
    <%= form.text_field :soNgay %>
  </div>

  <div>
    <%= form.label :ghiChu, style: "display: block" %>
    <%= form.text_field :ghiChu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/Blog/app/views/bookmanages/edit.html.erb
<h1>Editing bookmanage</h1>

<%= render "form", bookmanage: @bookmanage %>

<br>

<div>
  <%= link_to "Show this bookmanage", @bookmanage %> |
  <%= link_to "Back to bookmanages", bookmanages_path %>
</div>

Rails/Blog/app/views/bookmanages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookmanage_146</h1>

<div id="bookmanages">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Stt</th>
        <th scope="col">Mã HS</th>
        <th scope="col">Lớp</th>
        <th scope="col">Mã sãch</th>
        <th scope="col">Tên sách</th>
        <th scope="col">Tên tác giả</th>
        <th scope="col">Ngày mượn</th>
        <th scope="col">Ngày trả</th>
        <th scope="col">Số ngày</th>
        <th scope="col">Ghi chú</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @bookmanages.each do |bookmanage| %>
        <%= render bookmanage %>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New bookmanage", new_bookmanage_path %>

Rails/Blog/app/views/bookmanages/new.html.erb
<h1>New bookmanage</h1>

<%= render "form", bookmanage: @bookmanage %>

<br>

<div>
  <%= link_to "Back to bookmanages", bookmanages_path %>
</div>

Rails/Blog/app/views/bookmanages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bookmanage %>

<div>
  <%= link_to "Edit this bookmanage", edit_bookmanage_path(@bookmanage) %> |
  <%= link_to "Back to bookmanages", bookmanages_path %>

  <%= button_to "Destroy this bookmanage", @bookmanage, method: :delete %>
</div>

Rails/Blog/app/views/home/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark">NguyenHongSon</a>
  </div>
  <!-- Copyright -->
</footer>

Rails/Blog/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
        <%=  link_to 'BLOG', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%=  link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
            <%=  link_to "Post", home_post_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
            <%=  link_to "Book Manage", bookmanages_path, class:"nav-link active" %>
        </li>
    </div>
  </div>
</nav>

Rails/Blog/app/views/home/index.html.erb
<h1>This is home/index page</h1>

Rails/Blog/app/views/home/post.html.erb
<h1>This is home/post page</h1>

Rails/Blog/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>BLOG</title>
  </head>
  <body>
  
    <%= render 'home/header' %>
    <div class="container min-vh-100">
    <%= yield %>
    </div>
    <%= render 'home/footer' %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>